title: Error messages: howw to write them?
description: my final project
theme: just-the-docs

url: https://katgaj.github.io/final-project

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
